version: '3'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - '4200:4200'
      - '49153:49153'
    volumes:
      - ./frontend/package.json:/frontend/package.json
      - ./frontend/app:/frontend/app
      - ./frontend/config:/frontend/config
      - ./frontend/public:/frontend/public
      - ./frontend/tests:/frontend/tests
      - ./frontend/translations:/frontend/translations
    command: npm start
  backend:
    build:
      context: ./backend
    ports:
      - '3000:3000'
    volumes:
      - ./backend/Gemfile:/backend/Gemfile
      - ./backend/Gemfile.lock:/backend/Gemfile.lock
      - ./backend/Rakefile:/backend/Rakefile
      - ./backend/app:/backend/app
      - ./backend/config:/backend/config
      - ./backend/config.ru:/backend/config.ru
      - ./backend/db/migrate:/backend/db/migrate
      - ./backend/db/views:/backend/db/views
      - ./backend/db/schema.rb:/backend/db/schema.rb
      - ./backend/db/seeds.rb:/backend/db/seeds.rb
      - ./backend/lib:/backend/lib
      - ./backend/public:/backend/public
      - ./backend/spec:/backend/spec
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USERNAME=postgres
      - REDIS_URL=redis://redis:6379
    links:
      - db
      - redis
    command: bin/rails s -b 0.0.0.0
  sidekiq:
    build:
      context: ./backend
    links:
      - redis
      - db
    command: bundle exec sidekiq
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USERNAME=postgres
      - REDIS_URL=redis://redis:6379
  db:
    image: postgres:9.6
    environment:
      - POSTGRES_DB=rundfunk-backend-development
  redis:
    image: redis:3.2.0
